In [1]:
# Using Drive as storage and github for version controll.

from google.colab import drive, userdata
import os

# 1. Mount Drive
drive.mount('/content/drive')

# 2. Setup Paths (Change to your actual repo name)
REPO_PATH = "/content/drive/MyDrive/ML/DL_With_Pytorch"
%cd {REPO_PATH}

# 3. Secure Auth
token = userdata.get('GH_TOKEN')
username = "barada02"
repo = "DL_With_Pytorch"
!git remote set-url origin https://{token}@github.com/{username}/{repo}.git

# 4. Identity
!git config --global user.email "Chandanbarada2@gmail.com"
!git config --global user.name "Kumar"

!git pull origin main
print("✅ Environment Ready!")

Mounted at /content/drive
/content/drive/MyDrive/ML/DL_With_Pytorch
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 940 bytes | 1024 bytes/s, done.
From https://github.com/barada02/DL_With_Pytorch
 * branch            main       -> FETCH_HEAD
   2cfe18a..2f17d93  main       -> origin/main
Updating 2cfe18a..2f17d93
Fast-forward
 README.md | 11 +----------
 1 file changed, 1 insertion(+), 10 deletions(-)
✅ Environment Ready!


In [25]:
# Push notebook changes to GitHub
# IMPORTANT: Press Ctrl+S (Save) before running this!
!git add .
!git commit -m "concat"
!git push origin main

[main 02cc268] concat
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite 01_Tensors_02_operations.ipynb (64%)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.81 KiB | 154.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/barada02/DL_With_Pytorch.git
   4a4011c..02cc268  main -> main


# Note book starts from here

In [4]:

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


# Tensor operations

* By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using ```.to``` method (after checking for accelerator availability).
* Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [ ]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

## Standard numpy-like indexing and slicking:

In [8]:
tensor = torch.ones(3,3)
print(tensor)
print(tensor.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [9]:
print(f"First row:{tensor[0]}")
print(f"First coloumn:{tensor[:,0]}")
print(f"Last coloumn:{tensor[...,-1]}")
tensor[:,1]=0 #slicing and assignment.In-place Operation: This modifies the original tensor. It doesn't create a new one;
print(tensor)


First row:tensor([1., 1., 1.])
First coloumn:tensor([1., 1., 1.])
Last coloumn:tensor([1., 1., 1.])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


## Joining Tensors
You can use ```torch.cat``` to concatenate a sequence of tensors along a given dimension. See also ```torch.stack```, another tensor joining operator that is subtly different from ```torch.cat```

In [27]:
import torch

# t1 is 2 rows, 3 columns
t1 = torch.full((2, 3), 1.0)
# t2 is 4 rows, 3 columns
t2 = torch.full((4, 3), 2.0)

# They match in the second dimension (3), so we can stack them vertically
vertical_stack = torch.cat([t1, t2], dim=0)

print(f"Tensor 1 Shape: {t1.shape}")
print(f"Tensor 2 Shape: {t2.shape}")
print(f"Result Shape:   {vertical_stack.shape}")
print("\nResulting Tensor:\n", vertical_stack)

Tensor 1 Shape: torch.Size([2, 3])
Tensor 2 Shape: torch.Size([4, 3])
Result Shape:   torch.Size([6, 3])

Resulting Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [17]:
t3 = torch.cat([t1,t1,t1],dim=1)
print(t3)

tensor([[-1.4317, -0.9568, -0.4488, -1.4317, -0.9568, -0.4488, -1.4317, -0.9568,
         -0.4488],
        [ 0.9543,  0.2966, -0.4342,  0.9543,  0.2966, -0.4342,  0.9543,  0.2966,
         -0.4342],
        [-0.0089, -0.7056, -0.9768, -0.0089, -0.7056, -0.9768, -0.0089, -0.7056,
         -0.9768]])


In [20]:
t4 = torch.randn(2,2,2)
print(t4)
t5 = torch.randn(2,2,2)
print(t5)

tensor([[[-1.0604,  0.7685],
         [ 0.8733,  0.4160]],

        [[-1.9874,  0.3755],
         [ 0.0278,  0.5052]]])
tensor([[[ 0.1598, -1.0132],
         [-0.1319,  0.2742]],

        [[ 0.6721, -0.5150],
         [-0.2022, -1.4717]]])


In [21]:
torch.cat([t4,t5],dim=0)

tensor([[[-1.0604,  0.7685],
         [ 0.8733,  0.4160]],

        [[-1.9874,  0.3755],
         [ 0.0278,  0.5052]],

        [[ 0.1598, -1.0132],
         [-0.1319,  0.2742]],

        [[ 0.6721, -0.5150],
         [-0.2022, -1.4717]]])

In [22]:
torch.cat([t4,t5],dim=1)

tensor([[[-1.0604,  0.7685],
         [ 0.8733,  0.4160],
         [ 0.1598, -1.0132],
         [-0.1319,  0.2742]],

        [[-1.9874,  0.3755],
         [ 0.0278,  0.5052],
         [ 0.6721, -0.5150],
         [-0.2022, -1.4717]]])

In [24]:
torch.cat([t4,t5],dim=2)

tensor([[[-1.0604,  0.7685,  0.1598, -1.0132],
         [ 0.8733,  0.4160, -0.1319,  0.2742]],

        [[-1.9874,  0.3755,  0.6721, -0.5150],
         [ 0.0278,  0.5052, -0.2022, -1.4717]]])



> Concatenates the given sequence of tensors in tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be a 1-D empty tensor with size (0,).

>```torch.cat()``` can be seen as an inverse operation for ```torch.split()``` and ```torch.chunk()```.

>```torch.cat()``` can be best understood via examples.



In [26]:
import torch

# t1 is 2 rows, 3 columns
t1 = torch.full((2, 3), 1.0)
# t2 is 4 rows, 3 columns
t2 = torch.full((4, 3), 2.0)

# They match in the second dimension (3), so we can stack them vertically
vertical_stack = torch.cat([t1, t2], dim=0)

print(f"Tensor 1 Shape: {t1.shape}")
print(f"Tensor 2 Shape: {t2.shape}")
print(f"Result Shape:   {vertical_stack.shape}")
print("\nResulting Tensor:\n", vertical_stack)

Tensor 1 Shape: torch.Size([2, 3])
Tensor 2 Shape: torch.Size([4, 3])
Result Shape:   torch.Size([6, 3])

Resulting Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


## Arithmetic Operations

In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)