In [1]:
# Using Drive as storage and github for version controll.

from google.colab import drive, userdata
import os

# 1. Mount Drive
drive.mount('/content/drive')

# 2. Setup Paths (Change to your actual repo name)
REPO_PATH = "/content/drive/MyDrive/ML/DL_With_Pytorch"
%cd {REPO_PATH}

# 3. Secure Auth
token = userdata.get('GH_TOKEN')
username = "barada02"
repo = "DL_With_Pytorch"
!git remote set-url origin https://{token}@github.com/{username}/{repo}.git

# 4. Identity
!git config --global user.email "Chandanbarada2@gmail.com"
!git config --global user.name "Kumar"

!git pull origin main
print("✅ Environment Ready!")

Mounted at /content/drive
/content/drive/MyDrive/ML/DL_With_Pytorch
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 940 bytes | 1024 bytes/s, done.
From https://github.com/barada02/DL_With_Pytorch
 * branch            main       -> FETCH_HEAD
   2cfe18a..2f17d93  main       -> origin/main
Updating 2cfe18a..2f17d93
Fast-forward
 README.md | 11 +----------
 1 file changed, 1 insertion(+), 10 deletions(-)
✅ Environment Ready!


### Commit and push

In [58]:
# Push notebook changes to GitHub
# IMPORTANT: Press Ctrl+S (Save) before running this!
!git add .
!git commit -m "Single-element tensors "
!git push origin main

[main b77d96c] Broadcasting
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite 01_Tensors_02_operations.ipynb (87%)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.14 KiB | 117.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/barada02/DL_With_Pytorch.git
   325729a..b77d96c  main -> main


# Note book starts from here

In [4]:

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


# Tensor operations

* By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using ```.to``` method (after checking for accelerator availability).
* Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [ ]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

## Standard numpy-like indexing and slicking:

In [8]:
tensor = torch.ones(3,3)
print(tensor)
print(tensor.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [9]:
print(f"First row:{tensor[0]}")
print(f"First coloumn:{tensor[:,0]}")
print(f"Last coloumn:{tensor[...,-1]}")
tensor[:,1]=0 #slicing and assignment.In-place Operation: This modifies the original tensor. It doesn't create a new one;
print(tensor)


First row:tensor([1., 1., 1.])
First coloumn:tensor([1., 1., 1.])
Last coloumn:tensor([1., 1., 1.])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


## Joining Tensors
You can use ```torch.cat``` to concatenate a sequence of tensors along a given dimension. See also ```torch.stack```, another tensor joining operator that is subtly different from ```torch.cat```

In [32]:
# When dim=0, the columns must be identical.

# t1 is 2 rows, 3 columns
t1 = torch.randn(2, 3)
# t2 is 4 rows, 3 columns
t2 = torch.full((4, 3), 2.0)

# They match in the second dimension (3), so we can stack them vertically
vertical_stack = torch.cat([t1, t2], dim=0)

print(f"Tensor 1 Shape: {t1.shape}")
print(f"Tensor 2 Shape: {t2.shape}")
print(f"Result Shape:   {vertical_stack.shape}")
print("\nResulting Tensor:\n", vertical_stack)

Tensor 1 Shape: torch.Size([2, 3])
Tensor 2 Shape: torch.Size([4, 3])
Result Shape:   torch.Size([6, 3])

Resulting Tensor:
 tensor([[ 2.6525,  0.0903,  0.6860],
        [-1.0292,  0.6796, -0.2612],
        [ 2.0000,  2.0000,  2.0000],
        [ 2.0000,  2.0000,  2.0000],
        [ 2.0000,  2.0000,  2.0000],
        [ 2.0000,  2.0000,  2.0000]])


In [33]:
# When dim=1, the rows must be identical.

# t1 is 2 rows, 3 columns
# t1 = torch.rand(2, 3)
# t3 is 2 rows, 5 columns
t3 = torch.full((2, 5), 3.0)

# They match in the first dimension (2), so we can glue them side-by-side
horizontal_stack = torch.cat([t1, t3], dim=1)

print(f"Tensor 1 Shape: {t1.shape}")
print(f"Tensor 3 Shape: {t3.shape}")
print(f"Result Shape:   {horizontal_stack.shape}")
print("\nResulting Tensor:\n", horizontal_stack)

Tensor 1 Shape: torch.Size([2, 3])
Tensor 3 Shape: torch.Size([2, 5])
Result Shape:   torch.Size([2, 8])

Resulting Tensor:
 tensor([[ 2.6525,  0.0903,  0.6860,  3.0000,  3.0000,  3.0000,  3.0000,  3.0000],
        [-1.0292,  0.6796, -0.2612,  3.0000,  3.0000,  3.0000,  3.0000,  3.0000]])


In [20]:
t4 = torch.randn(2,2,2)
print(t4)
t5 = torch.randn(2,2,2)
print(t5)

tensor([[[-1.0604,  0.7685],
         [ 0.8733,  0.4160]],

        [[-1.9874,  0.3755],
         [ 0.0278,  0.5052]]])
tensor([[[ 0.1598, -1.0132],
         [-0.1319,  0.2742]],

        [[ 0.6721, -0.5150],
         [-0.2022, -1.4717]]])


In [21]:
torch.cat([t4,t5],dim=0)

tensor([[[-1.0604,  0.7685],
         [ 0.8733,  0.4160]],

        [[-1.9874,  0.3755],
         [ 0.0278,  0.5052]],

        [[ 0.1598, -1.0132],
         [-0.1319,  0.2742]],

        [[ 0.6721, -0.5150],
         [-0.2022, -1.4717]]])

In [22]:
torch.cat([t4,t5],dim=1)

tensor([[[-1.0604,  0.7685],
         [ 0.8733,  0.4160],
         [ 0.1598, -1.0132],
         [-0.1319,  0.2742]],

        [[-1.9874,  0.3755],
         [ 0.0278,  0.5052],
         [ 0.6721, -0.5150],
         [-0.2022, -1.4717]]])

In [24]:
torch.cat([t4,t5],dim=2)

tensor([[[-1.0604,  0.7685,  0.1598, -1.0132],
         [ 0.8733,  0.4160, -0.1319,  0.2742]],

        [[-1.9874,  0.3755,  0.6721, -0.5150],
         [ 0.0278,  0.5052, -0.2022, -1.4717]]])



> Concatenates the given sequence of tensors in tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be a 1-D empty tensor with size (0,).

>```torch.cat()``` can be seen as an inverse operation for ```torch.split()``` and ```torch.chunk()```.

>```torch.cat()``` can be best understood via examples.



#### mismatch

In [34]:
t_a = torch.randn(2, 3) # Width 3
t_b = torch.randn(2, 4) # Width 4

print("Attempting to concat (2,3) and (2,4) on dim=0...")
try:
    # This will fail because you can't stack a width of 3 on a width of 4
    error_stack = torch.cat([t_a, t_b], dim=0)
except RuntimeError as e:
    print(f"\nCaught Expected Error: \n{e}")

Attempting to concat (2,3) and (2,4) on dim=0...

Caught Expected Error: 
Sizes of tensors must match except in dimension 0. Expected size 3 but got size 4 for tensor number 1 in the list.


* The 1-D Empty Tensor Exception
* This is how you "grow" a tensor starting from nothing.

In [35]:
# A 1-D empty tensor
collector = torch.tensor([])

# Data to add
item1 = torch.tensor([10, 20])
item2 = torch.tensor([30, 40, 50])

# First concat: empty + item1
collector = torch.cat([collector, item1], dim=0)
print(f"After 1st addition: {collector}")

# Second concat: item1 + item2
collector = torch.cat([collector, item2], dim=0)
print(f"After 2nd addition: {collector}")

After 1st addition: tensor([10., 20.])
After 2nd addition: tensor([10., 20., 30., 40., 50.])


#### Higher dimensions (3D)
In Deep Learning, we often use 3D (Sequence, Batch, Feature) or 4D (Batch, Channel, Height, Width). The rule stays the same: only the dimension you are joining can be different.

In [36]:
# Imagine two batches of images
# Shape: (Batch, Channel, Height, Width)
batch1 = torch.randn(16, 3, 64, 64)
batch2 = torch.randn(8, 3, 64, 64)

# Concatenate batches together
big_batch = torch.cat([batch1, batch2], dim=0)

print(f"Batch 1: {batch1.shape}")
print(f"Batch 2: {batch2.shape}")
print(f"Combined Batch: {big_batch.shape}") # (24, 3, 64, 64)

Batch 1: torch.Size([16, 3, 64, 64])
Batch 2: torch.Size([8, 3, 64, 64])
Combined Batch: torch.Size([24, 3, 64, 64])


#### Difference between ```.cat``` and ```.stack```

Think of it like this:

* **`.cat` (Concatenate):** Takes existing blocks and makes a **longer/wider** block. **(Dimension count stays the same).**
* **`.stack`:** Takes existing blocks and puts them in a **new box**. **(Dimension count increases)**.

---

### 1. The Core Difference

| Feature | `torch.cat` | `torch.stack` |
| --- | --- | --- |
| **Dimensions** | Stays the same (e.g., 2D remains 2D). | **Increases** by 1 (e.g., 1D becomes 2D). |
| **Rule** | Tensors must match in all dims except the one you join. | All tensors must be **exactly** the same shape. |
| **Analogy** | Taping two sheets of paper together side-by-side. | Putting two sheets of paper on top of each other to make a book. |

---



###  Which one should you use?

* Use **`.cat`** when you want to append data (like adding more rows to a dataset or **more features to a vector**).
* Use **`.stack`** when you have multiple separate samples (like 10 individual images) and you want to turn them into a single **batch**.

> **Pro Tip:** Stacking is actually the same as adding a new "fake" dimension using `.unsqueeze()` and then using `.cat`.

[Stack vs Concat in PyTorch, TensorFlow & NumPy](https://www.youtube.com/watch?v=kF2AlpykJGY)



In [42]:

# Notice the shape stays 1D, just longer.

import torch
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])

# Joining along the existing dimension
res_cat = torch.cat([t1, t2], dim=0)

print(f"Cat Shape: {res_cat.shape}") # Result: torch.Size([6])
print(f"dimension: {res_cat.dim()}")
print(f"Cat Result: {res_cat}")



Cat Shape: torch.Size([6])
dimension: 1
Cat Result: tensor([1, 2, 3, 4, 5, 6])


###  `torch.stack`

 Notice it creates a **new** dimension (it becomes 2D).

In [44]:

# Stacking them creates a "container" for both
res_stack = torch.stack([t1, t2], dim=0)

print(f"Stack Shape: {res_stack.shape}") # Result: torch.Size([2, 3])
print(f"dimension: {res_stack.dim()}")
print("")
print(f"Stack Result:\n{res_stack}")


Stack Shape: torch.Size([2, 3])
dimension: 2

Stack Result:
tensor([[1, 2, 3],
        [4, 5, 6]])


## Arithmetic Operations

#### Matrix Multiplication

In [53]:
tensor = torch.full((2, 2),5)
print(tensor)

tensor([[5, 5],
        [5, 5]])


In [56]:


# --- Matrix Multiplication (Dot Product) ---
# Results in a 2x2 matrix where each element is (5*5 + 5*5) = 50
mat_mu1 = tensor @ tensor.T
mat_mu2 = tensor.matmul(tensor.T)

mat_mu3 = torch.empty_like(mat_mu1) # Using empty_like is safer/faster
torch.matmul(tensor, tensor.T, out=mat_mu3)

# --- Element-wise Multiplication (Hadamard Product) ---
# Results in a 2x2 matrix where each element is (5*5) = 25
el_wise1 = tensor * tensor
el_wise2 = tensor.mul(tensor)

el_wise3 = torch.empty_like(tensor)
torch.mul(tensor, tensor, out=el_wise3)

print("Matrix Mult Result:\n", mat_mu1)
print("")
print("Element-wise Result:\n", el_wise1)

Matrix Mult Result:
 tensor([[50, 50],
        [50, 50]])

Element-wise Result:
 tensor([[25, 25],
        [25, 25]])




## 1. Matrix Multiplication (The Dot Product)

This operation follows the **row-by-column** rule. In your code, you used `tensor @ tensor.T`. If we represent the original tensor as , then the multiplication  is defined as:

**General Definition:**
For  and , the element at row  and column  is:


---

## 2. Element-wise Multiplication (The Hadamard Product)

In your code, you used `tensor * tensor`. This is the **Hadamard Product**, denoted by the symbol . It simply multiplies the numbers that are in the same position.

**General Definition:**
For , the resulting element is:


---

### Comparison Summary

| Property | Matrix Multiplication (`@`) | Element-wise (`*`) |
| --- | --- | --- |
| **Math Symbol** |  or  |  |
| **Pytorch** | `torch.matmul(A, B)` | `torch.mul(A, B)` |
| **Requirement** | Columns of  == Rows of  | Shapes must be identical* |
| **Operation** | Sum of products (Dot product) | Individual products |

> **Note on** `out=y3`: Mathematically, this is just an assignment: . In PyTorch, this is a memory-efficient way to perform the calculation by reusing an existing allocated memory block.


## 1. Matrix Multiplication (The Dot Product)

This operation follows the **row-by-column** rule. In your code, you used `tensor @ tensor.T`. If we represent the original tensor as , then the multiplication  is defined as:

**General Definition:**
For  and , the element at row  and column  is:


---

## 2. Element-wise Multiplication (The Hadamard Product)

In your code, you used `tensor * tensor`. This is the **Hadamard Product**, denoted by the symbol . It simply multiplies the numbers that are in the same position.

**General Definition:**
For , the resulting element is:


---

### Comparison Summary

| Property | Matrix Multiplication (`@`) | Element-wise (`*`) |
| --- | --- | --- |
| **Math Symbol** |  or  |  |
| **Pytorch** | `torch.matmul(A, B)` | `torch.mul(A, B)` |
| **Requirement** | Columns of  == Rows of  | Shapes must be identical* |
| **Operation** | Sum of products (Dot product) | Individual products |

> **Note on `out=y3**`: Mathematically, this is just an assignment: . In PyTorch, this is a memory-efficient way to perform the calculation by reusing an existing allocated memory block.


##Single-element tensors
If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using ```item():```

In [61]:
print(tensor, tensor.dtype)
agg = tensor.sum()
print(agg, agg.dtype)

tensor([[5, 5],
        [5, 5]]) torch.int64
tensor(20) torch.int64


In [59]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

20 <class 'int'>
