In [4]:

from google.colab import drive, userdata
import os

# 1. Mount Drive
drive.mount('/content/drive')

# 2. Setup Paths (Change to your actual repo name)
REPO_PATH = "/content/drive/MyDrive/ML/DL_With_Pytorch"
%cd {REPO_PATH}

# 3. Secure Auth
token = userdata.get('GH_TOKEN')
username = "barada02"
repo = "DL_With_Pytorch"
!git remote set-url origin https://{token}@github.com/{username}/{repo}.git

# 4. Identity
!git config --global user.email "Chandanbarada2@gmail.com"
!git config --global user.name "Kumar"

!git pull origin main
print("✅ Environment Ready!")


Mounted at /content/drive
/content/drive/MyDrive/ML/DL_With_Pytorch
From https://github.com/barada02/DL_With_Pytorch
 * branch            main       -> FETCH_HEAD
Already up to date.
✅ Environment Ready!


In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Pytorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


# Tensors
## Creating tensor using ```torch.tensor()```

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [7]:
type(scalar)

torch.Tensor

In [6]:
scalar.item() # got as python int

7

#### vector

In [8]:
data = [5,7]
v = torch.tensor(data)
v

tensor([5, 7])

In [14]:
print(type(v))
v.ndim


<class 'torch.Tensor'>


1

In [15]:
v.shape

torch.Size([2])

#### Matrix

In [16]:
m_data = [[6,9],[8,8]]
m = torch.tensor(m_data)
m

tensor([[6, 9],
        [8, 8]])

In [17]:
m.ndim

2

In [18]:
m.shape

torch.Size([2, 2])

In [19]:
m[0]

tensor([6, 9])

#### Tensor

In [28]:
t_data = [[[6,5],[7,2],[15,78]]]

t = torch.tensor(t_data)
t

tensor([[[ 6,  5],
         [ 7,  2],
         [15, 78]]])

In [29]:
t.shape # 3 row 2 coloumns

torch.Size([1, 3, 2])

1 (Dimension 0): The number of matrices (often the Batch Size).

3 (Dimension 1): The number of Rows in each matrix.

2 (Dimension 2): The number of Columns in each matrix.

In [30]:
t.ndim

3

## Update the repo

In [31]:
# 2. Push notebook changes to GitHub
# IMPORTANT: Press Ctrl+S (Save) before running this!
!git add .
!git commit -m "tensor dimension "
!git push origin main

[main ea5cc0e] tensor dimension
 1 file changed, 1 insertion(+), 1 deletion(-)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.07 KiB | 83.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/barada02/DL_With_Pytorch.git
   ee3558f..ea5cc0e  main -> main
